### ISSUE TITLE
g8 foundweekends/giter8.g8 does not produce a working SBT project

### ISSUE THREAD

**Issue by EmilDafinov** [foundweekends/giter8.g8#10]
Hello, 
I tried creating a g8 template repo using : 
`g8 foundweekends/giter8.g8`

I used the default values for all parameters. However, when I
`cd my-template-project`
and I try running sbt I get the following error:

```
[info] Loading global plugins from /Users/emil.dafinov/.sbt/0.13/plugins
[info] Loading project definition from /Users/emil.dafinov/my-template-project/project
/Users/emil.dafinov/my-template-project/build.sbt:8: error: not found: value g8Test
      val _ = (g8Test in Test).toTask("").value
               ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Giter8 version: `0.10.0`

**Comment by xuwei-k** [comment]
I can't reproduce this problem. There is already `addSbtPlugin` settings in `src/main/g8/project/giter8.sbt`

https://github.com/foundweekends/giter8.g8/blob/145a5336b4b02af5a40ed3679a694e7672d0f789/src/main/g8/project/giter8.sbt#L1
